Program Data_Screen;
{This was the main routine for database query search and retrieve using the object toolkit}

Uses DOS, CRT, totFAST, totREAL, totINPUT, totIO1, totIO2, totIO3,
	 totSTR, totDATE, totMSG;

Var
	SearchFormOBJ	: WinFormOBJ;
	CriteriaOBJ : CheckIOOBJ;
	SearchNameOBJ : LateralIOOBJ;
	SearchDateOBJ : DateIOOBJ;
	SearchAddressOBJ : LateralIOOBJ;
	SearchTownOBJ	: LateralIOOBJ;
	SearchPhoneOBJ	: PictureIOOBJ;
	SearchGoOBJ		: Strip3DIOOBJ;
	SearchCancelOBJ : Strip3DIOOBJ;
Begin
End.